# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  #config.vm.provider "virtualbox"
  #config.vm.box = "kalilinux/rolling"
  config.vm.define "kali" do |kali|
    kali.vm.box = "kalilinux/rolling"
    kali.vm.hostname = "kali"
    kali.vm.box_url = "https://app.vagrantup.com/kalilinux/boxes/rolling"
    kali.vm.box_version = "2024.3.1"
    #kali.vm.network "private_network", ip: "192.168.100.10"
    kali.vm.provider "virtualbox" do |v|
      #v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      #v.customize ["modifyvm", :id, "--cableconnected1", "on"]
      v.customize ["modifyvm", :id, "--memory", 4096]
      v.customize ["modifyvm", :id, "--name", "kali"]
      v.customize ["modifyvm", :id, "--cpus", "2"]
    end
	kali.vm.provision "shell", path: "prerequisites.sh"
	#kali.vm.provision "shell", reboot: "true"
  kali.vm.provision :reload, reboot: true
  end
  #config.vm.provision "kali" :reboot
end